name: smallholder-env
channels:
  - conda-forge
  - defaults
  - r
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - joblib
  - statsmodels
  - geopandas
  - osmnx
  - folium
  - contextily
  - dcor
  - pytorch
  - torchvision
  - torchaudio
  - r-base=4.3
  - r-dplyr
  - r-efatools
  - r-boot
  - r-gifi
  - r-lavaan
  - r-mgcv
  - r-polycor
  - r-psych
  - r-readxl
  - r-stringr
  - r-dosnow
  - r-foreach
  - r-ggplot2
  - r-reshape2
  - r-semtools
  - pip
  - pip:
      - gower==0.1.2
      - numdifftools==0.9.41
      - semopy==2.3.11
